### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by Markvy** [reneeb/HTTP-Tiny-Multipart#4]
I think the line after line 158, here:

https://github.com/reneeb/HTTP-Tiny-Multipart/blob/master/lib/HTTP/Tiny/Multipart.pm#L158

Should be a blank line, or else the formatting gets messed up, as can be seen here:

https://metacpan.org/pod/HTTP::Tiny::Multipart

**Comment by reneeb** [comment]
Thanks for this bug report. It was fixed in f7bb282 and the new version should hit CPAN within a couple of minutes...
